name: Deploy Docs
on: push

jobs:
  build:
    name: Build HTML
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Generate HTML from Markdown
        uses: ldeluigi/markdown-docs@latest
        with:
          src: .
          dst: generated
          title: Markdown Docs
          language: en
          icon: library
          primary-color: indigo
          secondary-color: indigo
          hide-repository: false

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v2

  deploy:
    name: Deploy Notes
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2